export const REVIEW_AND_FILTER_TABLE_DATA = [
  {
    "id": 1,
    "conversationId": "13542f16-c2ff-4383-9c59-4c9c60b5c523",
    "customerIntent": "Lost or undelivered package",
    "businessOutcome": ["Risk & Crisis Management", "Reduced Customer Effort", "Enhanced Brand Trust", "Improved CLV / Conversion Rate"],
    "customerSentiment": "frustrated",
    "predictedAgentId": "52a37e5837f160ee6dab4a4e224adda87b7207fbe462c18da5720a709fd0342e",
    "predictedAgentName": "Emily",
    "predictedAgentPersona": "Empathetic Advisor - Specializes in understanding customer frustration, providing reassurance, and offering flexible solutions with supportive communication",
    "predictedAgentPersonaConfidence": "95%",
    "reasonForPrediction": "Customer experiencing shipping delays with time constraints requires high empathy, proactive problem-solving, and clear expectation management. This agent is top-ranked in Empathetic Advisor persona with proven ability to handle complex shipping issues while maintaining supportive communication throughout multiple solution paths.",
    "actualAgentId": "93d461313a6a2fd3821e96db1216702e06d950fcb32cfcc7565221a66195bcc6",
    "actualAgentName": "Sarah",
    "actualAgentPersona": "Empathetic Advisor - Ranked 3rd in persona, demonstrated good empathetic skills and solution-oriented approach",
    "actualAgentPersonaConfidence": "72%"
  },
  {
    "id": 2,
    "conversationId": "7ba07363-c607-4d27-b591-9d509a44f7b5",
    "customerIntent": "Order status inquiry",
    "businessOutcome": ["Reduced Customer Effort", "Enhanced Brand Trust", "Improved CLV / Conversion Rate"],
    "customerSentiment": "concerned",
    "predictedAgentId": "dfef416c34bbdd17d45b346ae122d5052cc318363872a15805ec3559d6ba9797",
    "predictedAgentName": "Alex",
    "predictedAgentPersona": "Efficient Resolver - Focuses on quick problem identification and resolution with clear communication",
    "predictedAgentPersonaConfidence": "90%",
    "reasonForPrediction": "Customer needs tracking information update - straightforward inquiry requiring efficient information gathering and clear communication about warehouse issues. Top-ranked Efficient Resolver can quickly diagnose and provide solution timeline.",
    "actualAgentId": "55ca6df7c9625112278fc1c7270a7a9b9a816eb044dba70d4302692745b2e690",
    "actualAgentName": "Jordan",
    "actualAgentPersona": "Brand Ambassador - Well-rounded agent with strong communication skills",
    "actualAgentPersonaConfidence": "78%"
  },
  {
    "id": 3,
    "conversationId": "3135516e-9c2d-4de7-9ee3-2bc0c48f5222",
    "customerIntent": "Request return or refund",
    "businessOutcome": ["Risk & Crisis Management", "Recovered Sales / Lower Return Rates", "Enhanced Brand Trust"],
    "customerSentiment": "disappointed",
    "predictedAgentId": "c91a8b96aea3a6c74d46c3c233dc8f43ca748a21744f703cc9e37f1a6d331bb1",
    "predictedAgentName": "Morgan",
    "predictedAgentPersona": "MultiPersona agent (Efficient Resolver + Empathetic Advisor) - Can handle system issues while providing emotional support",
    "predictedAgentPersonaConfidence": "88%",
    "reasonForPrediction": "Lost package situation requiring both empathy for customer disappointment and efficient processing of refund due to system glitch. MultiPersona agent can address both emotional and procedural needs effectively.",
    "actualAgentId": "55ca6df7c9625112278fc1c7270a7a9b9a816eb044dba70d4302692745b2e690",
    "actualAgentName": "Jordan",
    "actualAgentPersona": "Brand Ambassador - Well-rounded agent with strong communication skills",
    "actualAgentPersonaConfidence": "75%"
  },
  {
    "id": 4,
    "conversationId": "7fe347ff-dbae-4df9-8aad-d9bc90654f54",
    "customerIntent": "Promo code or discount issues",
    "businessOutcome": ["Upsell & Cross-Sell Conversions", "Improved CLV / Conversion Rate", "Campaign Effectiveness"],
    "customerSentiment": "neutral",
    "predictedAgentId": "f0b1bb1c8a55eacf6b7b3dc30da9232caa19ec3e11d5c98bb009bc5ae0b47d49",
    "predictedAgentName": "Taylor",
    "predictedAgentPersona": "Brand Ambassador - Excellent at promoting brand benefits, explaining policies, and converting potential sales",
    "predictedAgentPersonaConfidence": "92%",
    "reasonForPrediction": "Customer seeking purchase assistance with discount codes and free shipping - perfect opportunity for brand education, policy explanation, and conversion optimization. Top Brand Ambassador can maximize this sales opportunity.",
    "actualAgentId": "55ca6df7c9625112278fc1c7270a7a9b9a816eb044dba70d4302692745b2e690",
    "actualAgentName": "Jordan",
    "actualAgentPersona": "Brand Ambassador - Well-rounded agent with strong communication skills",
    "actualAgentPersonaConfidence": "80%"
  },
  {
    "id": 5,
    "conversationId": "f8c29e51-bfca-49c3-85ce-8ff9a57d7f32",
    "customerIntent": "Promo code or discount issues",
    "businessOutcome": ["Campaign Effectiveness", "Improved CLV / Conversion Rate", "Enhanced Brand Trust"],
    "customerSentiment": "neutral",
    "predictedAgentId": "f5e489f49596094b3f993b2f821448c11f0608a403b74d01f54942bd0e2af193",
    "predictedAgentName": "Riley",
    "predictedAgentPersona": "Brand Ambassador - Skilled in product knowledge and promotional code assistance",
    "predictedAgentPersonaConfidence": "90%",
    "reasonForPrediction": "Straightforward promo code issue requiring quick resolution and alternative code provision. Second-ranked Brand Ambassador can efficiently resolve code conflicts while maintaining positive customer experience.",
    "actualAgentId": "55ca6df7c9625112278fc1c7270a7a9b9a816eb044dba70d4302692745b2e690",
    "actualAgentName": "Jordan",
    "actualAgentPersona": "Brand Ambassador - Well-rounded agent with strong communication skills",
    "actualAgentPersonaConfidence": "85%"
  },
  {
    "id": 6,
    "conversationId": "c022e010-9284-4c95-82d9-68149c7a2b30",
    "customerIntent": "Request return or refund",
    "businessOutcome": ["Reduced Customer Effort", "Enhanced Brand Trust", "Improved CLV / Conversion Rate"],
    "customerSentiment": "polite",
    "predictedAgentId": "c7f03a5f420c0f8f80731da30c9055c0c0e4fc5a7636e2b6a47d62b58f0e068b",
    "predictedAgentName": "Casey",
    "predictedAgentPersona": "ProcessFocused Agent - Excellent at following return procedures and creating shipping labels efficiently",
    "predictedAgentPersonaConfidence": "95%",
    "reasonForPrediction": "Simple return label request from polite customer - requires efficient process execution and clear procedural communication. ProcessFocused Agent can handle this routine request with high accuracy and speed.",
    "actualAgentId": "510bcec108734240c69276bc42820b7c81690a6177fed4ebff12a8ee31b62c81",
    "actualAgentName": "Sam",
    "actualAgentPersona": "Potential Trainee - Shows good customer service basics but may need guidance on complex procedures",
    "actualAgentPersonaConfidence": "60%"
  },
  {
    "id": 7,
    "conversationId": "15943e70-684f-41d7-8fec-039ec9d570b9",
    "customerIntent": "Product warranty claim",
    "businessOutcome": ["Enhanced Brand Trust", "Improved Product Quality Feedback Loop", "Reduced Customer Effort"],
    "customerSentiment": "frustrated",
    "predictedAgentId": "c7f03a5f420c0f8f80731da30c9055c0c0e4fc5a7636e2b6a47d62b58f0e068b",
    "predictedAgentName": "Casey",
    "predictedAgentPersona": "ProcessFocused Agent - Specialized in warranty procedures and technical issue resolution",
    "predictedAgentPersonaConfidence": "90%",
    "reasonForPrediction": "Warranty code validation issue requires technical troubleshooting and process knowledge. ProcessFocused Agent can efficiently diagnose system issues and guide customer through proper warranty procedures.",
    "actualAgentId": "cd0c62c02296d0bc77630e68e043044471cf6eb7c88202734db15088c45a9e8a",
    "actualAgentName": "Drew",
    "actualAgentPersona": "Potential Trainee - Demonstrates basic problem-solving but conversation was incomplete",
    "actualAgentPersonaConfidence": "45%"
  },
  {
    "id": 8,
    "conversationId": "e71713e0-04d8-4066-aef5-e3c12fa9cb0f",
    "customerIntent": "Account or membership issues",
    "businessOutcome": ["Enhanced Brand Trust", "Improved CLV / Conversion Rate", "Campaign Effectiveness"],
    "customerSentiment": "frustrated",
    "predictedAgentId": "52a37e5837f160ee6dab4a4e224adda87b7207fbe462c18da5720a709fd0342e",
    "predictedAgentName": "Emily",
    "predictedAgentPersona": "Empathetic Advisor - Excellent at handling system limitations with customer-focused solutions",
    "predictedAgentPersonaConfidence": "92%",
    "reasonForPrediction": "Technical account creation issue due to name format requiring empathy for customer frustration and creative problem-solving. Top Empathetic Advisor can provide alternative solutions while maintaining positive relationship.",
    "actualAgentId": "cd0c62c02296d0bc77630e68e043044471cf6eb7c88202734db15088c45a9e8a",
    "actualAgentName": "Drew",
    "actualAgentPersona": "Potential Trainee - Shows good customer service approach and provided promotional code solution",
    "actualAgentPersonaConfidence": "65%"
  },
  {
    "id": 9,
    "conversationId": "23550e70-8452-47f5-b86b-eb27c3bf6746",
    "customerIntent": "Product information request",
    "businessOutcome": ["Better Product Fit & Usage Guidance", "Upsell & Cross-Sell Conversions", "Market Expansion Clues"],
    "customerSentiment": "neutral",
    "predictedAgentId": "f517d03a9409f0a50d782d4ed219e9f8177728cb9e53ac55481ec834ff8cc417",
    "predictedAgentName": "Quinn",
    "predictedAgentPersona": "Brand Ambassador - Strong product knowledge and ability to guide customers to suitable alternatives",
    "predictedAgentPersonaConfidence": "88%",
    "reasonForPrediction": "Product availability inquiry requiring deep product knowledge and ability to suggest alternatives. Third-ranked Brand Ambassador can provide comprehensive product information and guide customer to available options.",
    "actualAgentId": "cd0c62c02296d0bc77630e68e043044471cf6eb7c88202734db15088c45a9e8a",
    "actualAgentName": "Drew",
    "actualAgentPersona": "Potential Trainee - Provided basic product information but could have offered more comprehensive guidance",
    "actualAgentPersonaConfidence": "55%"
  },
  {
    "id": 10,
    "conversationId": "7dc1cfb7-01ac-4387-88cc-d85d9e318812",
    "customerIntent": "First-time customer discount",
    "businessOutcome": ["Campaign Effectiveness", "Improved CLV / Conversion Rate", "Enhanced Brand Trust"],
    "customerSentiment": "polite",
    "predictedAgentId": "f292c881719cd621570dccbee7e4044329bb12642e5c05480bca0dfa40d659de",
    "predictedAgentName": "Harper",
    "predictedAgentPersona": "Brand Ambassador - Specialized in first responder programs and promotional campaigns",
    "predictedAgentPersonaConfidence": "93%",
    "reasonForPrediction": "First responder discount inquiry requiring knowledge of special programs and promotional alternatives. Fourth-ranked Brand Ambassador can effectively communicate program changes and provide suitable alternatives to maintain goodwill.",
    "actualAgentId": "aba7a54f18775fed4ea7c8a0e241be415faee19b78c6767e86cf0e856b74e0c7",
    "actualAgentName": "Parker",
    "actualAgentPersona": "Efficient Resolver (67% match) - Handled the inquiry well by providing alternative promotional code",
    "actualAgentPersonaConfidence": "75%"
  },
  {
    "id": 11,
    "conversationId": "df7917f7-93c8-4fa2-ba41-029e34cf34fb",
    "customerIntent": "Product information request",
    "businessOutcome": ["Market Expansion Clues", "Better Product Fit & Usage Guidance", "Enhanced Brand Trust"],
    "customerSentiment": "helpful",
    "predictedAgentId": "e9cc916e4718955f88f072820f8e9b325802c96a1e4b7a756df9cee0a48911f9",
    "predictedAgentName": "Blake",
    "predictedAgentPersona": "Brand Ambassador - Knowledgeable about donation programs and community outreach procedures",
    "predictedAgentPersonaConfidence": "87%",
    "reasonForPrediction": "Donation inquiry for disaster relief requiring knowledge of corporate giving procedures and ability to provide appropriate contact information. Fifth-ranked Brand Ambassador can handle community outreach inquiries professionally.",
    "actualAgentId": "aba7a54f18775fed4ea7c8a0e241be415faee19b78c6767e86cf0e856b74e0c7",
    "actualAgentName": "Parker",
    "actualAgentPersona": "Efficient Resolver (67% match) - Provided correct donation process information efficiently",
    "actualAgentPersonaConfidence": "80%"
  },
  {
    "id": 12,
    "conversationId": "3e199296-8787-4f5d-87a2-ac9e84dea6d1",
    "customerIntent": "Request return or refund",
    "businessOutcome": ["Reduced Customer Effort", "Enhanced Brand Trust", "Improved CLV / Conversion Rate"],
    "customerSentiment": "neutral",
    "predictedAgentId": "d550e63a1e445345bafda3987041eaa54d6159a0434704ad93672e4b5a5beb97",
    "predictedAgentName": "Cameron",
    "predictedAgentPersona": "ProcessFocused Agent - Excellent at order lookup procedures and return label generation",
    "predictedAgentPersonaConfidence": "95%",
    "reasonForPrediction": "Routine return request requiring customer verification and return label creation. ProcessFocused Agent can efficiently handle order lookup, customer verification, and label generation with high accuracy.",
    "actualAgentId": "aba7a54f18775fed4ea7c8a0e241be415faee19b78c6767e86cf0e856b74e0c7",
    "actualAgentName": "Parker",
    "actualAgentPersona": "Efficient Resolver (67% match) - Successfully processed return and provided clear instructions",
    "actualAgentPersonaConfidence": "85%"
  },
  {
    "id": 13,
    "conversationId": "427c8205-a65f-44ee-b7de-94573119be01",
    "customerIntent": "Product information request",
    "businessOutcome": ["Better Product Fit & Usage Guidance", "Upsell & Cross-Sell Conversions", "Enhanced Brand Trust"],
    "customerSentiment": "neutral",
    "predictedAgentId": "e889c83950ec4595a11747e78c8fbf84419f841ad821845b0fecb3c4816e7636",
    "predictedAgentName": "Avery",
    "predictedAgentPersona": "Brand Ambassador - Strong product knowledge and ability to explain product specifications and compatibility",
    "predictedAgentPersonaConfidence": "90%",
    "reasonForPrediction": "Product specification inquiry about Cross Town backpack requiring detailed product knowledge and ability to connect legacy products with current offerings. Sixth-ranked Brand Ambassador can provide comprehensive product education.",
    "actualAgentId": "aba7a54f18775fed4ea7c8a0e241be415faee19b78c6767e86cf0e856b74e0c7",
    "actualAgentName": "Parker",
    "actualAgentPersona": "Efficient Resolver (67% match) - Provided accurate product information linking old and new models",
    "actualAgentPersonaConfidence": "82%"
  },
  {
    "id": 14,
    "conversationId": "638425f9-faf0-495c-8c7b-d9b28ad05f6e",
    "customerIntent": "Product warranty claim",
    "businessOutcome": ["Enhanced Brand Trust", "Improved Product Quality Feedback Loop", "Risk & Crisis Management"],
    "customerSentiment": "concerned",
    "predictedAgentId": "2f1e6c9c03adff2f0ad3b99438c40eb1f25034e97f3f0863d6e7833deedf103b",
    "predictedAgentName": "Sage",
    "predictedAgentPersona": "ProcessFocused Agent - Specialized in warranty evaluation procedures and damage assessment",
    "predictedAgentPersonaConfidence": "92%",
    "reasonForPrediction": "Warranty claim for washing machine damage requiring careful evaluation of coverage and clear explanation of warranty process. ProcessFocused Agent can navigate complex warranty scenarios and set proper expectations.",
    "actualAgentId": "aba7a54f18775fed4ea7c8a0e241be415faee19b78c6767e86cf0e856b74e0c7",
    "actualAgentName": "Parker",
    "actualAgentPersona": "Efficient Resolver (67% match) - Provided warranty information and process guidance effectively",
    "actualAgentPersonaConfidence": "78%"
  },
  {
    "id": 15,
    "conversationId": "fd667574-0fb0-42b9-8660-82ec1120a711",
    "customerIntent": "Request return or refund",
    "businessOutcome": ["Risk & Crisis Management", "Enhanced Brand Trust", "Improved CLV / Conversion Rate"],
    "customerSentiment": "disappointed",
    "predictedAgentId": "76f89f554756a82039c07407f9217d3d2d0abd99a97d9e65ee137f7c12b7749e",
    "predictedAgentName": "Jordan",
    "predictedAgentPersona": "MultiPersona agent (Brand Ambassador + Efficient Resolver + Empathetic Advisor) - Can handle delivery issues with both efficiency and empathy",
    "predictedAgentPersonaConfidence": "94%",
    "reasonForPrediction": "Fast delivery failure requiring both empathy for customer disappointment and efficient refund processing. MultiPersona agent can address emotional needs while quickly resolving the delivery issue and processing refund.",
    "actualAgentId": "0ad7515f42de75755ed7109cbdae5215cac141d5dcd0b2d9e10ce171a0e9ed6d",
    "actualAgentName": "Alex",
    "actualAgentPersona": "Brand Ambassador - Handled the situation professionally and processed refund efficiently",
    "actualAgentPersonaConfidence": "85%"
  },
  {
    "id": 16,
    "conversationId": "25ad44bb-5ef8-4808-9b8e-f648b9af6d70",
    "customerIntent": "Promo code or discount issues",
    "businessOutcome": ["Campaign Effectiveness", "Upsell & Cross-Sell Conversions", "Improved CLV / Conversion Rate"],
    "customerSentiment": "confused",
    "predictedAgentId": "e0dfd8519566a4afeb07a254b052be06b68ab5f360a016f8c25382e2c7c37f63",
    "predictedAgentName": "Reese",
    "predictedAgentPersona": "Brand Ambassador - Excellent at explaining promotional policies and finding alternative solutions",
    "predictedAgentPersonaConfidence": "91%",
    "reasonForPrediction": "Complex promotional code issue requiring detailed policy explanation and alternative code provision. Seventh-ranked Brand Ambassador can navigate promotional restrictions while providing suitable alternatives to complete the sale.",
    "actualAgentId": "0ad7515f42de75755ed7109cbdae5215cac141d5dcd0b2d9e10ce171a0e9ed6d",
    "actualAgentName": "Alex",
    "actualAgentPersona": "Brand Ambassador - Successfully explained promotional restrictions and provided working alternative code",
    "actualAgentPersonaConfidence": "88%"
  },
  {
    "id": 17,
    "conversationId": "8d1063ef-df55-4e9d-b98f-89f1cf6c4c7a",
    "customerIntent": "Cancel order",
    "businessOutcome": ["Risk & Crisis Management", "Reduced Customer Effort", "Enhanced Brand Trust"],
    "customerSentiment": "frustrated",
    "predictedAgentId": "c91a8b96aea3a6c74d46c3c233dc8f43ca748a21744f703cc9e37f1a6d331bb1",
    "predictedAgentName": "Morgan",
    "predictedAgentPersona": "MultiPersona agent (Efficient Resolver + Empathetic Advisor) - Can quickly process cancellation while addressing customer frustration",
    "predictedAgentPersonaConfidence": "93%",
    "reasonForPrediction": "Order cancellation due to extended delay requiring both empathy for customer frustration and efficient refund processing. MultiPersona agent can address emotional concerns while quickly resolving the cancellation request.",
    "actualAgentId": "0ad7515f42de75755ed7109cbdae5215cac141d5dcd0b2d9e10ce171a0e9ed6d",
    "actualAgentName": "Alex",
    "actualAgentPersona": "Brand Ambassador - Processed cancellation efficiently and showed understanding of customer concerns",
    "actualAgentPersonaConfidence": "80%"
  },
  {
    "id": 18,
    "conversationId": "cde81ae0-dd05-468d-93ca-ccd326417867",
    "customerIntent": "Shipping or delivery inquiries",
    "businessOutcome": ["Reduced Customer Effort", "Enhanced Brand Trust", "Risk & Crisis Management"],
    "customerSentiment": "concerned",
    "predictedAgentId": "af73a2e125e7db57febdb30723adcae4f8a49bdfed968ea1cb63f4a7085b6f54",
    "predictedAgentName": "Robin",
    "predictedAgentPersona": "Efficient Resolver - Skilled at coordinating with warehouse and providing delivery updates",
    "predictedAgentPersonaConfidence": "89%",
    "reasonForPrediction": "Shipping inquiry requiring coordination with warehouse and clear communication about delivery timelines. Third-ranked Efficient Resolver can effectively manage logistics coordination and provide realistic delivery estimates.",
    "actualAgentId": "0ad7515f42de75755ed7109cbdae5215cac141d5dcd0b2d9e10ce171a0e9ed6d",
    "actualAgentName": "Alex",
    "actualAgentPersona": "Brand Ambassador - Provided warehouse coordination and clear timeline communication",
    "actualAgentPersonaConfidence": "78%"
  },
  {
    "id": 19,
    "conversationId": "1c268e43-588d-4528-b49a-8b3a56fc9dba",
    "customerIntent": "Shipping or delivery inquiries",
    "businessOutcome": ["Enhanced Brand Trust", "Reduced Customer Effort", "Risk & Crisis Management"],
    "customerSentiment": "frustrated",
    "predictedAgentId": "922495c9bbcef84a5f3067bd0fd9bf312c857fb594da27fdbdf925dea04c7519",
    "predictedAgentName": "Kai",
    "predictedAgentPersona": "Empathetic Advisor - Excellent at handling shipping delays with express service recovery",
    "predictedAgentPersonaConfidence": "92%",
    "reasonForPrediction": "Express shipping failure requiring both empathy for customer frustration and proactive service recovery through shipping refund. Empathetic Advisor can address disappointment while providing tangible compensation for the service failure.",
    "actualAgentId": "0ad7515f42de75755ed7109cbdae5215cac141d5dcd0b2d9e10ce171a0e9ed6d",
    "actualAgentName": "Alex",
    "actualAgentPersona": "Brand Ambassador - Provided shipping refund and warehouse coordination effectively",
    "actualAgentPersonaConfidence": "82%"
  },
  {
    "id": 20,
    "conversationId": "c38c4a8e-8d13-456e-b7e7-f2b204466879",
    "customerIntent": "Product information request",
    "businessOutcome": ["Better Product Fit & Usage Guidance", "Enhanced Brand Trust", "Upsell & Cross-Sell Conversions"],
    "customerSentiment": "neutral",
    "predictedAgentId": "dc59b6167a5044fe578affc7dd8e6fab8ad755cc07b991e846e08fd5be4be936",
    "predictedAgentName": "Dakota",
    "predictedAgentPersona": "Brand Ambassador - Strong color consultation skills and product knowledge",
    "predictedAgentPersonaConfidence": "87%",
    "reasonForPrediction": "Color verification inquiry requiring detailed product knowledge and ability to provide accurate color descriptions. Eighth-ranked Brand Ambassador can provide comprehensive color guidance to help customer make informed purchasing decisions.",
    "actualAgentId": "0ad7515f42de75755ed7109cbdae5215cac141d5dcd0b2d9e10ce171a0e9ed6d",
    "actualAgentName": "Alex",
    "actualAgentPersona": "Brand Ambassador - Provided helpful color opinions and alternative suggestions",
    "actualAgentPersonaConfidence": "80%"
  },
  {
    "id": 21,
    "conversationId": "b808eaaf-db64-45a0-81ea-4efb80d3eb19",
    "customerIntent": "Account or membership issues",
    "businessOutcome": ["Market Expansion Clues", "Enhanced Brand Trust", "Improved CLV / Conversion Rate"],
    "customerSentiment": "neutral",
    "predictedAgentId": "10f3c44a13f3a651199b586a38197957ca804a84ed069026e9158fddd09cc582",
    "predictedAgentName": "Phoenix",
    "predictedAgentPersona": "ProcessFocused Agent - Specialized in B2B account management and dealer services",
    "predictedAgentPersonaConfidence": "95%",
    "reasonForPrediction": "B2B dealer inquiry requiring specialized knowledge of dealer services and proper departmental routing. ProcessFocused Agent can provide accurate information about dealer programs and appropriate contact channels.",
    "actualAgentId": "c11824985e20fa058b347c0d5dc9ef8a2b44bceaea1519ba95ea04d2cc949254",
    "actualAgentName": "River",
    "actualAgentPersona": "Brand Ambassador - Provided correct dealer services information and contact details",
    "actualAgentPersonaConfidence": "85%"
  },
  {
    "id": 22,
    "conversationId": "06ed5897-35db-49eb-afe3-980b72154304",
    "customerIntent": "Request return or refund",
    "businessOutcome": ["Risk & Crisis Management", "Enhanced Brand Trust", "Reduced Customer Effort"],
    "customerSentiment": "angry",
    "predictedAgentId": "52a37e5837f160ee6dab4a4e224adda87b7207fbe462c18da5720a709fd0342e",
    "predictedAgentName": "Emily",
    "predictedAgentPersona": "Empathetic Advisor - Excellent at de-escalating angry customers and resolving system issues",
    "predictedAgentPersonaConfidence": "95%",
    "reasonForPrediction": "Angry customer with faulty product and escalating communication requiring high-level de-escalation skills and immediate problem resolution. Top Empathetic Advisor can calm the situation while addressing the underlying order issue.",
    "actualAgentId": "c11824985e20fa058b347c0d5dc9ef8a2b44bceaea1519ba95ea04d2cc949254",
    "actualAgentName": "River",
    "actualAgentPersona": "Brand Ambassador - Attempted to help but customer escalated due to order not being found",
    "actualAgentPersonaConfidence": "45%"
  },
  {
    "id": 23,
    "conversationId": "91952ea7-e95a-4ae3-a83b-2130b27d529e",
    "customerIntent": "Account or membership issues",
    "businessOutcome": ["Market Expansion Clues", "Enhanced Brand Trust", "Upsell & Cross-Sell Conversions"],
    "customerSentiment": "polite",
    "predictedAgentId": "06b7429d2d01e2e21b77bab0b19236b14a44e1c4d5e1a5b83ce5cf6589096c43",
    "predictedAgentName": "Sage",
    "predictedAgentPersona": "ProcessFocused Agent - Specialized in B2B partnerships and wholesale inquiries",
    "predictedAgentPersonaConfidence": "93%",
    "reasonForPrediction": "B2B retail partnership inquiry requiring knowledge of wholesale procedures and dealer services routing. ProcessFocused Agent can properly direct wholesale inquiries to appropriate business development channels.",
    "actualAgentId": "c11824985e20fa058b347c0d5dc9ef8a2b44bceaea1519ba95ea04d2cc949254",
    "actualAgentName": "River",
    "actualAgentPersona": "Brand Ambassador - Correctly routed to dealer services for wholesale inquiry",
    "actualAgentPersonaConfidence": "85%"
  },
  {
    "id": 24,
    "conversationId": "425f91fb-cfc3-40e2-8856-17141382c3a6",
    "customerIntent": "Product information request",
    "businessOutcome": ["Market Expansion Clues", "Enhanced Brand Trust", "Better Product Fit & Usage Guidance"],
    "customerSentiment": "enthusiastic",
    "predictedAgentId": "d9371304760e4599b2a3e5721d5b03a85f8a2d5741bfb83fa811d3da59a19524",
    "predictedAgentName": "River",
    "predictedAgentPersona": "Brand Ambassador - Knowledgeable about community programs and donation procedures",
    "predictedAgentPersonaConfidence": "91%",
    "reasonForPrediction": "Community donation inquiry requiring knowledge of corporate giving programs and proper routing procedures. Ninth-ranked Brand Ambassador can provide accurate information about donation processes while maintaining positive community relations.",
    "actualAgentId": "c11824985e20fa058b347c0d5dc9ef8a2b44bceaea1519ba95ea04d2cc949254",
    "actualAgentName": "River",
    "actualAgentPersona": "Brand Ambassador - Provided appropriate donation contact information efficiently",
    "actualAgentPersonaConfidence": "88%"
  },
  {
    "id": 25,
    "conversationId": "6d0b71d9-ea63-44bd-be93-eb564ac979b7",
    "customerIntent": "Product warranty claim",
    "businessOutcome": ["Enhanced Brand Trust", "Improved Product Quality Feedback Loop", "Reduced Customer Effort"],
    "customerSentiment": "disappointed",
    "predictedAgentId": "abcc8a50b05237ff0c143d839597d1ec07f09d41ded5b41c0f1ed87640b2d16b",
    "predictedAgentName": "Taylor",
    "predictedAgentPersona": "ProcessFocused Agent - Specialized in warranty procedures and quality issue documentation",
    "predictedAgentPersonaConfidence": "93%",
    "reasonForPrediction": "Early product failure warranty claim requiring thorough warranty process explanation and quality feedback documentation. ProcessFocused Agent can guide customer through warranty procedures while capturing important quality data.",
    "actualAgentId": "a64030a5b0a55036ae70f834d5f8e5f1527b367d23083de83d0b54207a6f35c2",
    "actualAgentName": "Quinn",
    "actualAgentPersona": "Potential Trainee - Provided basic warranty information but could have been more thorough",
    "actualAgentPersonaConfidence": "70%"
  },
  {
    "id": 26,
    "conversationId": "c6a09fa7-1e67-407f-a4ae-5badc28f3922",
    "customerIntent": "Order status inquiry",
    "businessOutcome": ["Reduced Customer Effort", "Enhanced Brand Trust", "Improved CLV / Conversion Rate"],
    "customerSentiment": "concerned",
    "predictedAgentId": "c91a8b96aea3a6c74d46c3c233dc8f43ca748a21744f703cc9e37f1a6d331bb1",
    "predictedAgentName": "Morgan",
    "predictedAgentPersona": "MultiPersona agent (Efficient Resolver + Empathetic Advisor) - Can handle order lookup and address customer concerns",
    "predictedAgentPersonaConfidence": "90%",
    "reasonForPrediction": "Missing order confirmation requiring both order investigation and reassurance about payment processing. MultiPersona agent can efficiently locate the order while addressing customer anxiety about the missing confirmation.",
    "actualAgentId": "a64030a5b0a55036ae70f834d5f8e5f1527b367d23083de83d0b54207a6f35c2",
    "actualAgentName": "Quinn",
    "actualAgentPersona": "Potential Trainee - Successfully located order and corrected email issue",
    "actualAgentPersonaConfidence": "75%"
  },
  {
    "id": 27,
    "conversationId": "8041d2ba-c0b3-4fe7-a4f6-81d30cc8e339",
    "customerIntent": "Product information request",
    "businessOutcome": ["Better Product Fit & Usage Guidance", "Sustainability Credibility", "Enhanced Brand Trust"],
    "customerSentiment": "concerned",
    "predictedAgentId": "f0333e61eb03feae121deffbf60d3957411e87d1f22946b4f95510186599f658",
    "predictedAgentName": "Casey",
    "predictedAgentPersona": "Brand Ambassador - Knowledgeable about product safety and materials information",
    "predictedAgentPersonaConfidence": "85%",
    "reasonForPrediction": "Product safety inquiry about BPA and toxic materials requiring detailed materials knowledge and ability to address health concerns. Tenth-ranked Brand Ambassador can provide accurate safety information while addressing customer health concerns professionally.",
    "actualAgentId": "a64030a5b0a55036ae70f834d5f8e5f1527b367d23083de83d0b54207a6f35c2",
    "actualAgentName": "Quinn",
    "actualAgentPersona": "Potential Trainee - Provided basic information but customer remained concerned about product safety",
    "actualAgentPersonaConfidence": "50%"
  }
]
