export const REVIEW_AND_FILTER_TABLE_DATA = [
  {
    "id": 1,
    "conversationId": "13542f16-c2ff-4383-9c59-4c9c60b5c523",
    "customerIntent": "Lost or undelivered package",
    "businessOutcome": ["Risk & Crisis Management", "Enhanced Brand Trust", "Reduced Customer Effort", "Improved CLV / Conversion Rate"],
    "customerSentiment": "frustrated",
    "predictedAgentId": "52a37e5837f160ee6dab4a4e224adda87b7207fbe462c18da5720a709fd0342e",
    "predictedAgentName": "Emily",
    "predictedAgentPersona": "Empathetic Advisor - Specializes in understanding customer frustration, providing reassurance, and offering flexible solutions with supportive communication",
    "predictedAgentPersonaConfidence": "95%",
    "reasonForPrediction": "Customer experiencing tracking issues with time constraints ('I do need it later this month') requires high empathy and proactive problem-solving. The agent offered multiple solutions (carrier investigation, re-send) while maintaining supportive communication, which aligns with risk management and trust-building outcomes.",
    "actualAgentId": "93d461313a6a2fd3821e96db1216702e06d950fcb32cfcc7565221a66195bcc6",
    "actualAgentName": "Sarah",
    "actualAgentPersona": "Empathetic Advisor - Ranked 3rd in persona, demonstrated good empathetic skills and solution-oriented approach",
    "actualAgentPersonaConfidence": "85%"
  },
  {
    "id": 2,
    "conversationId": "7ba07363-c607-4d27-b591-9d509a44f7b5",
    "customerIntent": "Order status inquiry",
    "businessOutcome": ["Reduced Customer Effort", "Enhanced Brand Trust", "Risk & Crisis Management"],
    "customerSentiment": "concerned",
    "predictedAgentId": "dfef416c34bbdd17d45b346ae122d5052cc318363872a15805ec3559d6ba9797",
    "predictedAgentName": "Marcus",
    "predictedAgentPersona": "Efficient Resolver - Focuses on quick problem identification and resolution with clear communication and systematic approach",
    "predictedAgentPersonaConfidence": "88%",
    "reasonForPrediction": "Customer has a straightforward tracking inquiry requiring quick resolution. The agent efficiently gathered order details, identified warehouse issue, and provided clear timeline expectations, demonstrating the systematic approach needed for operational efficiency.",
    "actualAgentId": "55ca6df7c9625112278fc1c7270a7a9b9a816eb044dba70d4302692745b2e690",
    "actualAgentName": "Alex",
    "actualAgentPersona": "Brand Ambassador - Demonstrated product knowledge and professional service delivery",
    "actualAgentPersonaConfidence": "75%"
  },
  {
    "id": 3,
    "conversationId": "3135516e-9c2d-4de7-9ee3-2bc0c48f5222",
    "customerIntent": "Request return or refund",
    "businessOutcome": ["Risk & Crisis Management", "Enhanced Brand Trust", "Reduced Customer Effort", "Recovered Sales / Lower Return Rates"],
    "customerSentiment": "frustrated",
    "predictedAgentId": "c91a8b96aea3a6c74d46c3c233dc8f43ca748a21744f703cc9e37f1a6d331bb1",
    "predictedAgentName": "Jordan",
    "predictedAgentPersona": "MultiPersona agent combining Empathetic Advisor, Efficient Resolver, and Brand Ambassador skills for complex issues",
    "predictedAgentPersonaConfidence": "92%",
    "reasonForPrediction": "Customer experienced system failure causing delayed refund, requiring empathy for frustration, efficiency in processing, and brand trust rebuilding. Agent apologized for system glitch, processed new refund immediately, and explained timeline clearly.",
    "actualAgentId": "55ca6df7c9625112278fc1c7270a7a9b9a816eb044dba70d4302692745b2e690",
    "actualAgentName": "Alex",
    "actualAgentPersona": "Brand Ambassador - Handled the situation professionally and maintained brand standards",
    "actualAgentPersonaConfidence": "78%"
  },
  {
    "id": 4,
    "conversationId": "7fe347ff-dbae-4df9-8aad-d9bc90654f54",
    "customerIntent": "Promo code or discount issues",
    "businessOutcome": ["Upsell & Cross-Sell Conversions", "Improved CLV / Conversion Rate", "Reduced Customer Effort", "Enhanced Brand Trust"],
    "customerSentiment": "neutral",
    "predictedAgentId": "f0b1bb1c8a55eacf6b7b3dc30da9232caa19ec3e11d5c98bb009bc5ae0b47d49",
    "predictedAgentName": "Taylor",
    "predictedAgentPersona": "Brand Ambassador - Excels at product knowledge, promotional guidance, and converting inquiries into sales while maintaining brand standards",
    "predictedAgentPersonaConfidence": "90%",
    "reasonForPrediction": "Customer needs promotional code assistance and purchasing guidance for multiple items. Agent provided detailed product information, explained promotion restrictions, offered alternative codes, and facilitated successful completion of large order.",
    "actualAgentId": "55ca6df7c9625112278fc1c7270a7a9b9a816eb044dba70d4302692745b2e690",
    "actualAgentName": "Alex",
    "actualAgentPersona": "Brand Ambassador - Demonstrated excellent product knowledge and promotional expertise",
    "actualAgentPersonaConfidence": "85%"
  },
  {
    "id": 5,
    "conversationId": "f8c29e51-bfca-49c3-85ce-8ff9a57d7f32",
    "customerIntent": "Promo code or discount issues",
    "businessOutcome": ["Improved CLV / Conversion Rate", "Reduced Customer Effort", "Enhanced Brand Trust", "Upsell & Cross-Sell Conversions"],
    "customerSentiment": "neutral",
    "predictedAgentId": "f5e489f49596094b3f993b2f821448c11f0608a403b74d01f54942bd0e2af193",
    "predictedAgentName": "Morgan",
    "predictedAgentPersona": "Brand Ambassador - Second-ranked, specializes in promotional support and conversion optimization",
    "predictedAgentPersonaConfidence": "87%",
    "reasonForPrediction": "Customer had simple promotional code issue needing quick resolution. Agent efficiently identified exclusions, provided alternative solution, and ensured customer satisfaction with minimal effort required.",
    "actualAgentId": "55ca6df7c9625112278fc1c7270a7a9b9a816eb044dba70d4302692745b2e690",
    "actualAgentName": "Alex",
    "actualAgentPersona": "Brand Ambassador - Handled promotion inquiry effectively with clear explanation",
    "actualAgentPersonaConfidence": "82%"
  },
  {
    "id": 6,
    "conversationId": "c022e010-9284-4c95-82d9-68149c7a2b30",
    "customerIntent": "Request return or refund",
    "businessOutcome": ["Reduced Customer Effort", "Enhanced Brand Trust", "Improved CLV / Conversion Rate", "Loyalty Program Growth"],
    "customerSentiment": "satisfied",
    "predictedAgentId": "dfef416c34bbdd17d45b346ae122d5052cc318363872a15805ec3559d6ba9797",
    "predictedAgentName": "Marcus",
    "predictedAgentPersona": "Efficient Resolver - Focuses on quick problem identification and systematic resolution processes",
    "predictedAgentPersonaConfidence": "90%",
    "reasonForPrediction": "Customer had straightforward return label request for wrong color. Agent efficiently processed the request with clear instructions and timeline, maintaining positive customer experience for future loyalty.",
    "actualAgentId": "510bcec108734240c69276bc42820b7c81690a6177fed4ebff12a8ee31b62c81",
    "actualAgentName": "River",
    "actualAgentPersona": "Potential Trainee - Handled basic return process adequately but could improve efficiency",
    "actualAgentPersonaConfidence": "65%"
  },
  {
    "id": 7,
    "conversationId": "15943e70-684f-41d7-8fec-039ec9d570b9",
    "customerIntent": "Product warranty claim",
    "businessOutcome": ["Enhanced Brand Trust", "Improved Product Quality Feedback Loop", "Risk & Crisis Management", "Reduced Customer Effort"],
    "customerSentiment": "frustrated",
    "predictedAgentId": "76f89f554756a82039c07407f9217d3d2d0abd99a97d9e65ee137f7c12b7749e",
    "predictedAgentName": "Casey",
    "predictedAgentPersona": "MultiPersona agent combining Brand Ambassador, Efficient Resolver, and Empathetic Advisor for warranty claims",
    "predictedAgentPersonaConfidence": "88%",
    "reasonForPrediction": "Customer experiencing warranty code issues requires technical support combined with empathy. Agent needs to maintain brand trust while efficiently resolving technical problems and gathering quality feedback.",
    "actualAgentId": "cd0c62c02296d0bc77630e68e043044471cf6eb7c88202734db15088c45a9e8a",
    "actualAgentName": "Quinn",
    "actualAgentPersona": "Potential Trainee - Session ended before resolution, indicating need for additional training",
    "actualAgentPersonaConfidence": "45%"
  },
  {
    "id": 8,
    "conversationId": "e71713e0-04d8-4066-aef5-e3c12fa9cb0f",
    "customerIntent": "Account or membership issues",
    "businessOutcome": ["Reduced Customer Effort", "Improved CLV / Conversion Rate", "Enhanced Brand Trust", "Loyalty Program Growth"],
    "customerSentiment": "frustrated",
    "predictedAgentId": "52a37e5837f160ee6dab4a4e224adda87b7207fbe462c18da5720a709fd0342e",
    "predictedAgentName": "Emily",
    "predictedAgentPersona": "Empathetic Advisor - Specializes in customer frustration management and flexible problem-solving",
    "predictedAgentPersonaConfidence": "85%",
    "reasonForPrediction": "Customer frustrated with account creation technical issue requiring empathy and creative problem-solving. Agent provided alternative solution (promotional code) when system limitations prevented standard resolution.",
    "actualAgentId": "cd0c62c02296d0bc77630e68e043044471cf6eb7c88202734db15088c45a9e8a",
    "actualAgentName": "Quinn",
    "actualAgentPersona": "Potential Trainee - Provided adequate solution but communication could be improved",
    "actualAgentPersonaConfidence": "70%"
  },
  {
    "id": 9,
    "conversationId": "23550e70-8452-47f5-b86b-eb27c3bf6746",
    "customerIntent": "Product information request",
    "businessOutcome": ["Better Product Fit & Usage Guidance", "Market Expansion Clues", "Improved Product Quality Feedback Loop", "Enhanced Brand Trust"],
    "customerSentiment": "neutral",
    "predictedAgentId": "f517d03a9409f0a50d782d4ed219e9f8177728cb9e53ac55481ec834ff8cc417",
    "predictedAgentName": "Avery",
    "predictedAgentPersona": "Brand Ambassador - Third-ranked, excels at product knowledge and customer education",
    "predictedAgentPersonaConfidence": "85%",
    "reasonForPrediction": "Customer seeking specific product availability information requires deep product knowledge and ability to provide alternatives. Agent successfully identified customer needs and provided detailed product information.",
    "actualAgentId": "cd0c62c02296d0bc77630e68e043044471cf6eb7c88202734db15088c45a9e8a",
    "actualAgentName": "Quinn",
    "actualAgentPersona": "Potential Trainee - Provided basic product information but lacked depth in product knowledge",
    "actualAgentPersonaConfidence": "60%"
  },
  {
    "id": 10,
    "conversationId": "7dc1cfb7-01ac-4387-88cc-d85d9e318812",
    "customerIntent": "First-time customer discount",
    "businessOutcome": ["Improved CLV / Conversion Rate", "Loyalty Program Growth", "Enhanced Brand Trust", "Upsell & Cross-Sell Conversions"],
    "customerSentiment": "satisfied",
    "predictedAgentId": "f292c881719cd621570dccbee7e4044329bb12642e5c05480bca0dfa40d659de",
    "predictedAgentName": "Blake",
    "predictedAgentPersona": "Brand Ambassador - Fourth-ranked, specialized in new customer acquisition and loyalty building",
    "predictedAgentPersonaConfidence": "88%",
    "reasonForPrediction": "First responder seeking discount information requires professional service that builds brand trust and converts inquiry into loyalty. Agent provided excellent service explaining discount limitations and offering alternative promotional code.",
    "actualAgentId": "aba7a54f18775fed4ea7c8a0e241be415faee19b78c6767e86cf0e856b74e0c7",
    "actualAgentName": "Dakota",
    "actualAgentPersona": "Efficient Resolver - Handled the request professionally and efficiently",
    "actualAgentPersonaConfidence": "82%"
  },
  {
    "id": 11,
    "conversationId": "df7917f7-93c8-4fa2-ba41-029e34cf34fb",
    "customerIntent": "Intent Not Found",
    "businessOutcome": ["Enhanced Brand Trust", "Risk & Crisis Management", "Market Expansion Clues", "Sustainability Credibility"],
    "customerSentiment": "helpful",
    "predictedAgentId": "e9cc916e4718955f88f072820f8e9b325802c96a1e4b7a756df9cee0a48911f9",
    "predictedAgentName": "Phoenix",
    "predictedAgentPersona": "Brand Ambassador - Fifth-ranked, excellent at handling unique requests and maintaining brand image",
    "predictedAgentPersonaConfidence": "85%",
    "reasonForPrediction": "Customer requesting donation information for disaster relief requires professional handling that maintains brand image and social responsibility. Agent provided proper contact information and process for donations.",
    "actualAgentId": "aba7a54f18775fed4ea7c8a0e241be415faee19b78c6767e86cf0e856b74e0c7",
    "actualAgentName": "Dakota",
    "actualAgentPersona": "Efficient Resolver - Handled donation inquiry professionally with proper routing",
    "actualAgentPersonaConfidence": "78%"
  },
  {
    "id": 12,
    "conversationId": "3e199296-8787-4f5d-87a2-ac9e84dea6d1",
    "customerIntent": "Request return or refund",
    "businessOutcome": ["Reduced Customer Effort", "Enhanced Brand Trust", "Improved CLV / Conversion Rate", "Loyalty Program Growth"],
    "customerSentiment": "neutral",
    "predictedAgentId": "af73a2e125e7db57febdb30723adcae4f8a49bdfed968ea1cb63f4a7085b6f54",
    "predictedAgentName": "Sage",
    "predictedAgentPersona": "Efficient Resolver - Second-ranked, combines brand ambassadorship with efficient resolution",
    "predictedAgentPersonaConfidence": "90%",
    "reasonForPrediction": "Customer needs return label for size issue requiring systematic order lookup and efficient processing. Agent successfully located order using alternative information and processed return quickly.",
    "actualAgentId": "aba7a54f18775fed4ea7c8a0e241be415faee19b78c6767e86cf0e856b74e0c7",
    "actualAgentName": "Dakota",
    "actualAgentPersona": "Efficient Resolver - Demonstrated excellent problem-solving and order management skills",
    "actualAgentPersonaConfidence": "87%"
  },
  {
    "id": 13,
    "conversationId": "638425f9-faf0-495c-8c7b-d9b28ad05f6e",
    "customerIntent": "Product warranty claim",
    "businessOutcome": ["Enhanced Brand Trust", "Improved Product Quality Feedback Loop", "Risk & Crisis Management", "Better Product Fit & Usage Guidance"],
    "customerSentiment": "concerned",
    "predictedAgentId": "e889c83950ec4595a11747e78c8fbf84419f841ad821845b0fecb3c4816e7636",
    "predictedAgentName": "Riley",
    "predictedAgentPersona": "Brand Ambassador - Sixth-ranked, combines efficient resolution with brand trust building",
    "predictedAgentPersonaConfidence": "85%",
    "reasonForPrediction": "Customer with washing machine damage needs warranty guidance requiring brand knowledge, empathy for accidental damage, and clear process explanation. Agent provided comprehensive warranty information and set proper expectations.",
    "actualAgentId": "aba7a54f18775fed4ea7c8a0e241be415faee19b78c6767e86cf0e856b74e0c7",
    "actualAgentName": "Dakota",
    "actualAgentPersona": "Efficient Resolver - Provided clear warranty process information and managed expectations well",
    "actualAgentPersonaConfidence": "80%"
  },
  {
    "id": 14,
    "conversationId": "427c8205-a65f-44ee-b7de-94573119be01",
    "customerIntent": "Product information request",
    "businessOutcome": ["Better Product Fit & Usage Guidance", "Enhanced Brand Trust", "Improved Product Quality Feedback Loop", "Reduced Customer Effort"],
    "customerSentiment": "satisfied",
    "predictedAgentId": "e0dfd8519566a4afeb07a254b052be06b68ab5f360a016f8c25382e2c7c37f63",
    "predictedAgentName": "Harper",
    "predictedAgentPersona": "Brand Ambassador - Seventh-ranked, efficient resolver specializing in product guidance",
    "predictedAgentPersonaConfidence": "88%",
    "reasonForPrediction": "Customer seeking product capacity information for college purchase requires detailed product knowledge and ability to reference current and discontinued models. Agent provided clear explanation of product evolution and equivalencies.",
    "actualAgentId": "aba7a54f18775fed4ea7c8a0e241be415faee19b78c6767e86cf0e856b74e0c7",
    "actualAgentName": "Dakota",
    "actualAgentPersona": "Efficient Resolver - Demonstrated strong product knowledge and clear communication",
    "actualAgentPersonaConfidence": "85%"
  },
  {
    "id": 15,
    "conversationId": "fd667574-0fb0-42b9-8660-82ec1120a711",
    "customerIntent": "Request return or refund",
    "businessOutcome": ["Risk & Crisis Management", "Enhanced Brand Trust", "Reduced Customer Effort", "Improved CLV / Conversion Rate"],
    "customerSentiment": "disappointed",
    "predictedAgentId": "0ad7515f42de75755ed7109cbdae5215cac141d5dcd0b2d9e10ce171a0e9ed6d",
    "predictedAgentName": "Jordan K.",
    "predictedAgentPersona": "Brand Ambassador - Twenty-sixth ranked, demonstrated strong service recovery and customer care",
    "predictedAgentPersonaConfidence": "90%",
    "reasonForPrediction": "Customer experienced delivery failure and needs refund for travel items requires service recovery, empathy, and efficient processing. Agent apologized for inconvenience, processed refund quickly, and maintained positive relationship.",
    "actualAgentId": "0ad7515f42de75755ed7109cbdae5215cac141d5dcd0b2d9e10ce171a0e9ed6d",
    "actualAgentName": "Jordan K.",
    "actualAgentPersona": "Brand Ambassador - Excellent service recovery, empathetic communication, and efficient resolution",
    "actualAgentPersonaConfidence": "92%"
  },
  {
    "id": 16,
    "conversationId": "25ad44bb-5ef8-4808-9b8e-f648b9af6d70",
    "customerIntent": "Shipping or delivery inquiries",
    "businessOutcome": ["Reduced Customer Effort", "Enhanced Brand Trust", "Upsell & Cross-Sell Conversions", "Improved CLV / Conversion Rate"],
    "customerSentiment": "confused",
    "predictedAgentId": "0ad7515f42de75755ed7109cbdae5215cac141d5dcd0b2d9e10ce171a0e9ed6d",
    "predictedAgentName": "Jordan K.",
    "predictedAgentPersona": "Brand Ambassador - Specializes in shipping explanations and promotional support",
    "predictedAgentPersonaConfidence": "88%",
    "reasonForPrediction": "Customer confused about shipping charges despite meeting minimum requires clear explanation of promotion terms and solution. Agent identified issue with sale items, provided free shipping code, and resolved concern efficiently.",
    "actualAgentId": "0ad7515f42de75755ed7109cbdae5215cac141d5dcd0b2d9e10ce171a0e9ed6d",
    "actualAgentName": "Jordan K.",
    "actualAgentPersona": "Brand Ambassador - Demonstrated excellent problem-solving and customer service skills",
    "actualAgentPersonaConfidence": "90%"
  },
  {
    "id": 17,
    "conversationId": "8d1063ef-df55-4e9d-b98f-89f1cf6c4c7a",
    "customerIntent": "Cancel order",
    "businessOutcome": ["Risk & Crisis Management", "Enhanced Brand Trust", "Reduced Customer Effort", "Improved CLV / Conversion Rate"],
    "customerSentiment": "impatient",
    "predictedAgentId": "c91a8b96aea3a6c74d46c3c233dc8f43ca748a21744f703cc9e37f1a6d331bb1",
    "predictedAgentName": "Jordan",
    "predictedAgentPersona": "MultiPersona agent combining empathetic advisor, efficient resolver, and brand ambassador skills",
    "predictedAgentPersonaConfidence": "92%",
    "reasonForPrediction": "Customer wanting to cancel after 10+ days due to delays requires empathy for frustration, efficient processing, and service recovery. Agent apologized, processed refund quickly, and maintained professional service throughout.",
    "actualAgentId": "0ad7515f42de75755ed7109cbdae5215cac141d5dcd0b2d9e10ce171a0e9ed6d",
    "actualAgentName": "Jordan K.",
    "actualAgentPersona": "Brand Ambassador - Handled cancellation professionally with empathy and efficiency",
    "actualAgentPersonaConfidence": "88%"
  },
  {
    "id": 18,
    "conversationId": "cde81ae0-dd05-468d-93ca-ccd326417867",
    "customerIntent": "Order status inquiry",
    "businessOutcome": ["Reduced Customer Effort", "Risk & Crisis Management", "Enhanced Brand Trust", "Better Product Fit & Usage Guidance"],
    "customerSentiment": "concerned",
    "predictedAgentId": "b7e35598462418350e6db1afcbf9a3da74a2f5659e7d98efa807db6f4a65f30c",
    "predictedAgentName": "Cameron",
    "predictedAgentPersona": "Efficient Resolver - Fourth-ranked, combines brand ambassadorship with systematic problem-solving",
    "predictedAgentPersonaConfidence": "85%",
    "reasonForPrediction": "Customer concerned about express shipping delay needs status update and timeline clarification. Agent contacted warehouse, provided updates, offered expedited solutions, and managed expectations professionally.",
    "actualAgentId": "0ad7515f42de75755ed7109cbdae5215cac141d5dcd0b2d9e10ce171a0e9ed6d",
    "actualAgentName": "Jordan K.",
    "actualAgentPersona": "Brand Ambassador - Provided excellent proactive communication and problem resolution",
    "actualAgentPersonaConfidence": "87%"
  },
  {
    "id": 19,
    "conversationId": "1c268e43-588d-4528-b49a-8b3a56fc9dba",
    "customerIntent": "Order status inquiry",
    "businessOutcome": ["Reduced Customer Effort", "Enhanced Brand Trust", "Risk & Crisis Management", "Recovered Sales / Lower Return Rates"],
    "customerSentiment": "anxious",
    "predictedAgentId": "94c669dc7b77166e0a87d23c2cbcb427b42f40e139ebb4ce043d6d95261c5134",
    "predictedAgentName": "Reese",
    "predictedAgentPersona": "Efficient Resolver - Fifth-ranked, combines brand ambassadorship with proactive problem-solving",
    "predictedAgentPersonaConfidence": "90%",
    "reasonForPrediction": "Customer anxious about express shipping status needs proactive communication and compensation. Agent investigated tracking issue, contacted warehouse, refunded express shipping fee, and provided clear timeline expectations.",
    "actualAgentId": "0ad7515f42de75755ed7109cbdae5215cac141d5dcd0b2d9e10ce171a0e9ed6d",
    "actualAgentName": "Jordan K.",
    "actualAgentPersona": "Brand Ambassador - Excellent proactive service and customer compensation handling",
    "actualAgentPersonaConfidence": "92%"
  },
  {
    "id": 20,
    "conversationId": "c38c4a8e-8d13-456e-b7e7-f2b204466879",
    "customerIntent": "Product information request",
    "businessOutcome": ["Better Product Fit & Usage Guidance", "Enhanced Brand Trust", "Improved Product Quality Feedback Loop", "Market Expansion Clues"],
    "customerSentiment": "neutral",
    "predictedAgentId": "dc59b6167a5044fe578affc7dd8e6fab8ad755cc07b991e846e08fd5be4be936",
    "predictedAgentName": "Skylar",
    "predictedAgentPersona": "Brand Ambassador - Eighth-ranked, efficient resolver specializing in product consultation",
    "predictedAgentPersonaConfidence": "85%",
    "reasonForPrediction": "Customer seeking color verification before purchase to avoid returns requires detailed product knowledge and color description expertise. Agent provided honest opinion and alternative suggestions to help customer make informed decision.",
    "actualAgentId": "0ad7515f42de75755ed7109cbdae5215cac141d5dcd0b2d9e10ce171a0e9ed6d",
    "actualAgentName": "Jordan K.",
    "actualAgentPersona": "Brand Ambassador - Provided helpful product guidance and honest color assessment",
    "actualAgentPersonaConfidence": "82%"
  },
  {
    "id": 21,
    "conversationId": "b808eaaf-db64-45a0-81ea-4efb80d3eb19",
    "customerIntent": "Intent Not Found",
    "businessOutcome": ["MultiBrand Portfolio Optimization", "Professional/B2B Segment Growth", "Enhanced Brand Trust", "Market Expansion Clues"],
    "customerSentiment": "professional",
    "predictedAgentId": "4fe252f4dbf523915c649550ca4876337916be73a511ac46a5343df3f451bd9f",
    "predictedAgentName": "Devon",
    "predictedAgentPersona": "Transactional Agent - Specializes in B2B inquiries and dealer services routing",
    "predictedAgentPersonaConfidence": "90%",
    "reasonForPrediction": "College bookstore seeking new sales representative requires B2B expertise and proper routing to dealer services. Agent provided correct department contact information for wholesale/educational accounts.",
    "actualAgentId": "c11824985e20fa058b347c0d5dc9ef8a2b44bceaea1519ba95ea04d2cc949254",
    "actualAgentName": "Sam",
    "actualAgentPersona": "Brand Ambassador - Handled B2B inquiry professionally with proper routing",
    "actualAgentPersonaConfidence": "75%"
  },
  {
    "id": 22,
    "conversationId": "06ed5897-35db-49eb-afe3-980b72154304",
    "customerIntent": "Request return or refund",
    "businessOutcome": ["Risk & Crisis Management", "Enhanced Brand Trust", "Reduced Customer Effort", "Improved CLV / Conversion Rate"],
    "customerSentiment": "angry",
    "predictedAgentId": "52a37e5837f160ee6dab4a4e224adda87b7207fbe462c18da5720a709fd0342e",
    "predictedAgentName": "Emily",
    "predictedAgentPersona": "Empathetic Advisor - Specializes in de-escalating angry customers and crisis management",
    "predictedAgentPersonaConfidence": "95%",
    "reasonForPrediction": "Customer extremely angry (using caps, demanding tone) about return label needs immediate de-escalation and empathetic handling. Requires top-tier empathetic advisor to manage crisis situation and restore brand trust.",
    "actualAgentId": "c11824985e20fa058b347c0d5dc9ef8a2b44bceaea1519ba95ea04d2cc949254",
    "actualAgentName": "Sam",
    "actualAgentPersona": "Brand Ambassador - Attempted professional response but escalation indicates need for empathetic approach",
    "actualAgentPersonaConfidence": "45%"
  },
  {
    "id": 23,
    "conversationId": "91952ea7-e95a-4ae3-a83b-2130b27d529e",
    "customerIntent": "Intent Not Found",
    "businessOutcome": ["MultiBrand Portfolio Optimization", "Professional/B2B Segment Growth", "Market Expansion Clues", "Enhanced Brand Trust"],
    "customerSentiment": "professional",
    "predictedAgentId": "2c67c0f66d11c5cb4004b9444396f034c8e530d9d1baa91b7d24cffcd5496154",
    "predictedAgentName": "River T.",
    "predictedAgentPersona": "Transactional Agent - Second-ranked, specializes in B2B partnerships and wholesale inquiries",
    "predictedAgentPersonaConfidence": "88%",
    "reasonForPrediction": "Business seeking wholesale partnership requires B2B expertise and proper routing to dealer services. Agent correctly routed to appropriate department for wholesale/partnership discussions.",
    "actualAgentId": "c11824985e20fa058b347c0d5dc9ef8a2b44bceaea1519ba95ea04d2cc949254",
    "actualAgentName": "Sam",
    "actualAgentPersona": "Brand Ambassador - Handled B2B partnership inquiry with proper routing procedures",
    "actualAgentPersonaConfidence": "78%"
  },
  {
    "id": 24,
    "conversationId": "425f91fb-cfc3-40e2-8856-17141382c3a6",
    "customerIntent": "Intent Not Found",
    "businessOutcome": ["Sustainability Credibility", "Enhanced Brand Trust", "Market Expansion Clues", "Brand Differentiation & Positioning"],
    "customerSentiment": "appreciative",
    "predictedAgentId": "d9371304760e4599b2a3e5721d5b03a85f8a2d5741bfb83fa811d3da59a19524",
    "predictedAgentName": "Rowan",
    "predictedAgentPersona": "Brand Ambassador - Ninth-ranked, specializes in community outreach and social responsibility",
    "predictedAgentPersonaConfidence": "85%",
    "reasonForPrediction": "University student requesting donation for community service requires professional handling that maintains brand image and social responsibility. Agent provided proper routing to donation team with supportive tone.",
    "actualAgentId": "c11824985e20fa058b347c0d5dc9ef8a2b44bceaea1519ba95ea04d2cc949254",
    "actualAgentName": "Sam",
    "actualAgentPersona": "Brand Ambassador - Handled donation request professionally with proper contact information",
    "actualAgentPersonaConfidence": "80%"
  },
  {
    "id": 25,
    "conversationId": "6d0b71d9-ea63-44bd-be93-eb564ac979b7",
    "customerIntent": "Product warranty claim",
    "businessOutcome": ["Enhanced Brand Trust", "Improved Product Quality Feedback Loop", "Risk & Crisis Management", "Better Product Fit & Usage Guidance"],
    "customerSentiment": "satisfied",
    "predictedAgentId": "f0333e61eb03feae121deffbf60d3957411e87d1f22946b4f95510186599f658",
    "predictedAgentName": "Finley",
    "predictedAgentPersona": "Brand Ambassador - Tenth-ranked, efficient resolver with warranty expertise",
    "predictedAgentPersonaConfidence": "90%",
    "reasonForPrediction": "Customer with product defect after minimal use needs warranty guidance and quality feedback collection. Agent provided comprehensive warranty information, clear process explanation, and maintained brand trust through lifetime guarantee messaging.",
    "actualAgentId": "a64030a5b0a55036ae70f834d5f8e5f1527b367d23083de83d0b54207a6f35c2",
    "actualAgentName": "Sage J.",
    "actualAgentPersona": "Potential Trainee - Provided adequate warranty information but could improve process explanation",
    "actualAgentPersonaConfidence": "70%"
  },
  {
    "id": 26,
    "conversationId": "c6a09fa7-1e67-407f-a4ae-5badc28f3922",
    "customerIntent": "Order status inquiry",
    "businessOutcome": ["Reduced Customer Effort", "Enhanced Brand Trust", "Improved CLV / Conversion Rate", "Risk & Crisis Management"],
    "customerSentiment": "concerned",
    "predictedAgentId": "8b7db565b8be2cce670841419ad230f676f37a242c3a34358dc8d26689a48470",
    "predictedAgentName": "Ash",
    "predictedAgentPersona": "Efficient Resolver - Sixth-ranked, combines brand ambassadorship with systematic order management",
    "predictedAgentPersonaConfidence": "88%",
    "reasonForPrediction": "Customer concerned about missing order confirmation needs systematic order lookup and clear communication. Agent located order despite email typo, resent confirmation, and maintained positive customer relationship.",
    "actualAgentId": "a64030a5b0a55036ae70f834d5f8e5f1527b367d23083de83d0b54207a6f35c2",
    "actualAgentName": "Sage J.",
    "actualAgentPersona": "Potential Trainee - Handled order lookup well but communication could be more proactive",
    "actualAgentPersonaConfidence": "75%"
  },
  {
    "id": 27,
    "conversationId": "8041d2ba-c0b3-4fe7-a4f6-81d30cc8e339",
    "customerIntent": "Product information request",
    "businessOutcome": ["Better Product Fit & Usage Guidance", "Sustainability Credibility", "Enhanced Brand Trust", "Product Innovation Feedback Loop"],
    "customerSentiment": "concerned_to_disappointed",
    "predictedAgentId": "52a37e5837f160ee6dab4a4e224adda87b7207fbe462c18da5720a709fd0342e",
    "predictedAgentName": "Emily",
    "predictedAgentPersona": "Empathetic Advisor - Specializes in handling sensitive topics and customer concerns about product safety",
    "predictedAgentPersonaConfidence": "85%",
    "reasonForPrediction": "Customer concerned about BPA/toxicity in children's backpacks requires empathetic handling of safety concerns and transparent communication. Agent provided available information but customer became upset about product safety implications, requiring high empathy skills.",
    "actualAgentId": "a64030a5b0a55036ae70f834d5f8e5f1527b367d23083de83d0b54207a6f35c2",
    "actualAgentName": "Sage J.",
    "actualAgentPersona": "Potential Trainee - Attempted to provide information but lacked empathy skills for sensitive safety concerns",
    "actualAgentPersonaConfidence": "50%"
  }
]
