export const CONVERSATION_DATA = [
  {
    id: 1,
    conversation: "CONV_001/2024-02-15",
    intent: "Payment Issue",
    originalTarget: "Agent John Doe (Billing)",
    llmTarget: "Bot GeneralBot",
    match: true,
    confidence: "94%",
    impact: "AHT: 8min > 2.7min",
    details: "View Details",
  },
  {
    id: 2,
    conversation: "CONV_001/2024-02-15",
    intent: "Payment Issue",
    originalTarget: "Agent John Doe (Billing)",
    llmTarget: "Bot GeneralBot",
    match: true,
    confidence: "94%",
    impact: "AHT: 8min > 2.7min",
    details: "View Details",
  },
  {
    id: 3,
    conversation: "CONV_001/2024-02-15",
    intent: "Payment Issue",
    originalTarget: "Agent John Doe (Billing)",
    llmTarget: "Bot GeneralBot",
    match: true,
    confidence: "94%",
    impact: "AHT: 8min > 2.7min",
    details: "View Details",
  },
  {
    id: 4,
    conversation: "CONV_001/2024-02-15",
    intent: "Payment Issue",
    originalTarget: "Agent John Doe (Billing)",
    llmTarget: "Bot GeneralBot",
    match: true,
    confidence: "94%",
    impact: "AHT: 8min > 2.7min",
    details: "View Details",
  },
  {
    id: 5,
    conversation: "CONV_001/2024-02-15",
    intent: "Payment Issue",
    originalTarget: "Agent John Doe (Billing)",
    llmTarget: "Bot GeneralBot",
    match: true,
    confidence: "94%",
    impact: "AHT: 8min > 2.7min",
    details: "View Details",
  },
]